### ISSUE TITLE
Implementation of Bubble sort

### ISSUE THREAD

**Issue by AaryaZ** [gdscpce/hacktober-codesnippet#1]
Write the code for Bubble Sort.

1. Follow and Read the Contributing Guidelines.
2. Only the assigned person is allowed to raise the PR on this Issue.
3. To get this issue assigned to you comment on this issue.

`Note:` The code can be written in any language of your choice.

**Comment by shahil-afroz** [comment]
plz assign this to me..

**Comment by MeetD99** [comment]
Hi, I would love to work on this Issue, can you Assign it to me please.

**Comment by deoraja** [comment]
Can u plz assign this to me @AaryaZ 
Rajashree Deokar TE IT B

**Comment by deoraja** [comment]
![image](https://github.com/gdscpce/hacktober-codesnippet/assets/115561757/ef5559e5-1480-4f7a-8c0f-518d1ad5a043)
 yes I have a solution can u please check it and assign it to me

**Comment by AaryaZ** [comment]
@deoraja please follow the contribution guidelines. Make a separate file. File name should be same as issue title.

**Comment by AaryaZ** [comment]
@deoraja The code you shared need few changes. The inner for loop doesn't have to iterate till len(list)-1.

**Comment by deoraja** [comment]
yes it worked and thank you so much for reviewing my code

**Comment by SachinChougule10** [comment]
> Write the code for Bubble Sort.
> 
> 1. Follow and Read the Contributing Guidelines.
> 2. Only the assigned person is allowed to raise the PR on this Issue.
> 3. To get this issue assigned to you comment on this issue.
> 
> `Note:` The code can be written in any language of your choice.

Plz assign me this issue

**Comment by SachinChougule10** [comment]
I will like  to work on this issue,plz assign me this issue.
