### ISSUE TITLE
 Add Code Snippet for Password Encryption, JWT Token Generation, and Password Reset func using mongoose schema method.

### ISSUE THREAD

**Issue by DrasticCoder** [gdscpce/hacktober-codesnippet#10]
## **Description:**
We need to add a code snippet to our "codesnippet" project that demonstrates how to securely handle user passwords, generate JWT tokens, and implement password reset functionality using Schema Methods.

___ 

**Details:**
I have identified the need for a code snippet that showcases the following key features:

**Password Encryption:** The code snippet should illustrate how to securely encrypt and store user passwords when they are registered or updated.

**JWT Token Generation:** Include a code snippet that demonstrates the generation of JWT (JSON Web Tokens) for user authentication and authorization purposes.

**Password Reset:** Implement a code snippet that allows users to reset their passwords securely, following best practices.

**Screenshots** : 

![Screenshot from 2023-10-08 20-15-25](https://github.com/gdscpce/hacktober-codesnippet/assets/86515544/982d416b-e182-4132-8622-ca19d6a666e3)

**Comment by DrasticCoder** [comment]
Maintainers, kindly assign this issue to me, [DrasticCoder](https://github.com/DrasticCoder)

Deep Bansode, SY comp C

**Comment by ypratham** [comment]
I would love to work on this issue.

**Pratham Yadav, TY comp B**
