### ISSUE TITLE
Product Array puzzle

### ISSUE THREAD

**Issue by AaryaZ** [gdscpce/hacktober-codesnippet#16]
`Problem:` Given an array of integers A, find and return the product array of the same size where the **i**th element of the product array will be equal to the product of all the elements divided by the **i**th element of the array.

**Solve it without using the division operator.**

![image](https://github.com/gdscpce/hacktober-codesnippet/assets/70696659/61d2d37c-fa88-4ed0-8e55-572d8b7d2912)

Follow and Read the Contributing Guidelines.

`Note:` The code can be written in any language of your choice.

**Comment by Suhaani07** [comment]
@AaryaZ kindly assign me this issue under hacktoberfest 2023. I'll be writing the code in Java

**Comment by Suhaani07** [comment]
@AaryaZ it's :
Name : Suhaani Aggarwal
Branch : Computer
Year : 3rd 
College name : Fr. C. Rodrigues Institute of Technology, Vashi (FCRIT)

Got to know about this repository since my college is one of the collaborating colleges.

**Comment by bhavanamn** [comment]
@AaryaZ kindly assign me this issue under hacktoberfest 2023. I'll be writing the code in Java
Name : M N BHAVANA
Branch : Computer ENGINEERING
Year : 3rd
College name :PILLAI COLLEGE OF ENGINEERING

**Comment by Suhaani07** [comment]
@AaryaZ have opened up the PR. Kindly check it out
