### ISSUE TITLE
Kadane's Algorithm. (Python)

### ISSUE THREAD

**Issue by AaryaZ** [gdscpce/hacktober-codesnippet#3]
`Problem:` Find the maximum sum of contiguous non-empty subarray within an array A of length N.

<img src="https://github.com/gdscpce/hacktober-codesnippet/assets/70696659/dc0fa46b-53ff-40b9-bd8d-7eb38e01d270" width="400" height="200"> 

Follow and Read the Contributing Guidelines.
To get this issue assigned to you comment on this issue.

- [ ] Follow and Read the Contributing Guidelines.
- [ ] The code must be submitted in the given programming language.

`Programming Language:` Python

**Comment by CHIRAGWADKAR** [comment]
Please assign this issue to me.
**CHIRAG WADKAR, PCE, SY, ECS B**

I have the solution to this issue.
![Screenshot (116)](https://github.com/gdscpce/hacktober-codesnippet/assets/89576084/3249e0ac-6cb4-4c45-9eba-8c12b827e28f)

**Comment by AaryaZ** [comment]
@CHIRAGWADKAR go with it.
please follow the contribution guidelines. Make a separate file. File name should be same as issue title.
